<?php
/**
 * @deprecated This file is a legacy remnant from the IGAPortal prototype.
 *
 * The correct example for CruinnCMS is config/CruinnCMS.example.php.
 * The real credential file generated by the install wizard is config/CruinnCMS.php.
 *
 * @see config/CruinnCMS.example.php
 */
